### ISSUE TITLE
Issue: Overlay Color Key broken when Frame Style = None

### ISSUE THREAD

**Issue by Civitello** [DarwinBaker/AATool#28]
Observed Behaviour:
When Overlay Frame Style is set to None there are many icons with surroundings that are a color slightly different than the selected BG color.

Steps to reproduce:
1. Launch AA tool
2. Select Settings
3. Select Overlay Tab
4. Check Enable Overlay Window
5. Under Appearance change Frame Style to None
6. Add the Stream Overlay window to OBS following the instructions
7. Observe the green surroundings visible on some items including Skulls and Debris

Expected behaviour:
The background of the Stream Overlay window should be perfectly uniform in color with no background surroundings on any items when filtered by OBS.

Attachment:
Attached you will find a cropped screenshot of a Wither Skull Icon where all #00AA00 Green has been filled with #FFFFFF White.
![aatool bug](https://user-images.githubusercontent.com/61434667/162340847-05b2024e-643d-4c50-a845-fff26c4eb40c.png)

**Comment by Civitello** [comment]
So, I am currently working on this issue, I have narrowed it down to the image files that are being used. They have semi-transparent pixels that are causing the issue. I am going to see if there's a way to batch process them to fix the issue.

**Comment by Civitello** [comment]
There appear to be 25 Advancements that are affected:
The End? 
Country Lode, Take Me Home
Not Quite "Nine" Lives
Who's Cutting Onions
War Pigs
Those Were The Days
A Terrible Fortress
Nether
Hidden in the Depths
Beaconator
Bring Home the Beacon
Spooky Scary Skeleton
Sweet Dreams
Sticky Situation
Bullseye
Voluntary Exile
Hero of the Village
Hired Help
The End
The Next Generation
City at the End of the Game
Husbandry
Total Beelocation
Minecraft
Not Today, Thank you

**Comment by DarwinBaker** [comment]
The partial transparency around these textures is just anti-aliasing and is intentional. It makes edges look better in every case except the one you've described. 
![image](https://user-images.githubusercontent.com/51175243/163754697-101a6226-90b4-4d52-820d-b92df25c6175.png)
As an example, right is with with anti-aliasing and left is without.

Since the vast majority of players use frames on their overlay, making these changes would be a visual downgrade for most users. Also this can be largely cleaned up just by tuning your filter settings in OBS, so I don't currently plan on changing these textures. I may add alternate textures specifically for this case, but there's currently a lot of stuff in development that's going to take priority.

I'd recommend adjusting similarity and smoothness and maybe try playing with your greenscreen color

**Comment by DarwinBaker** [comment]
Although the more I think about it the more I think this difference probably won't come across over stream bitrate anyway, so I think I will actually end up replacing these when I get the chance. I can just replace the 48x48px variants used for the overlay, which would leave the main window ones looking nice still. Only took me 10 more minutes to figure this out lmao

**Comment by DarwinBaker** [comment]
![image](https://user-images.githubusercontent.com/51175243/163782875-1ce2d958-cad4-467b-bf3b-aeef6c7f7d4a.png)
Made the changes, patch will be out soon :)

**Comment by Civitello** [comment]
Thanks so much, I spent an hour yesterday manually editing the images. I was very happy with the result and your solution looks even better! You could have both the aa ones for with frame and the non aa ones without the frame.
