### ISSUE TITLE
I connected to co-op but it doesn't track

### ISSUE THREAD

**Issue by 54ja** [DarwinBaker/AATool#57]
I was trying to do some achievement runs with my friend using hamachi and joining via lan. I can connect to co-op in the settings, but it doesn't track anything. How do i fix this.

**Comment by DarwinBaker** [comment]
Looks like this is a bug in the latest versions, I'll make sure to get a fix out as soon as I can. In the meantime I recommend using version 1.4.8.2 and just waiting to update until 1.5.2.0 is available which will contain the fix for this. Thanks for letting me know!

I tested and confirmed co-op mode works properly in this version:
https://github.com/DarwinBaker/AATool/releases/download/v1.4.8.2-revision/ctm_aatool_1.4.8.2.zip
